sudo: required
services:
    - docker

before_install:
    - docker build -t rbinwani/docker-react -f Dockerfile.dev .


script:
    - docker run rbinwani/docker-react npm run test -- --coverage


deploy:
    provider: elasticbeanstalk
region: "ap-south-1"
app: "Docker-react"
env: "DockerReact-env"
bucket_name: "elasticbeanstalk-ap-south-1-960200574380"
bucket_path: "Docker-react"
on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key:
    secure: "$AWS_SECRET_KEY